### ISSUE TITLE
Swagger parser error

### ISSUE THREAD

**Issue by shtrip** [vereniging-corponet/vera-openapi#1]
Als ik vanuit de README.md op het **vastgoed** linkje (onder Informatiedomeinen) klik, navigeert de browser naar [https://vereniging-corponet.github.io/vera-openapi/Informatiedomeinen/Vastgoed.html](https://vereniging-corponet.github.io/vera-openapi/Informatiedomeinen/Vastgoed.html). Op die Swagger pagina wordt een foutmelding getoond: 

> Parser error on line 5917
> duplicated mapping key

**Comment by peterjanvandeput** [comment]
Bedankt, is opgelost nu.
