### ISSUE TITLE
Referentiedata niet in binair formaat

### ISSUE THREAD

**Issue by DanielFortuyn** [vereniging-corponet/vera-openapi#10]
Omwille van het volgens van wijzigingen en om gebruik van third party apps zou het mooi zijn als de referentiedata in een ander formaat wordt opgeslagen. Bijvoorbeeld json of csv.

**Comment by renkosteenbeek** [comment]
Zie
https://github.com/vereniging-corponet/vera-referentiedata/blob/main/Referentiedata.csv

Het Excel document is overigens uitgebreider, hierin zit meer info dan alleen de referentie.
