### ISSUE TITLE
Gebruik van het 'id' veld als ingang tot een resource

### ISSUE THREAD

**Issue by cwiesenekker** [vereniging-corponet/vera-openapi#13]
Hallo werkgroep

Ik had een belangrijke vraag rondom het gebruik van het veld {id} als ingang tot een resource. Zover ik nu heb begrepen is de id het technische unieke nummer van een resource en is de 'code' het functioneel unieke nummer van een resource. Hoewel code niet perse uniek hoeft te zijn lees ik ook nergens dat ID dat ook moet zijn. Uiteraard impliceerd de keuze voor een ID in de resource dat dat zo is. 

Binnen het huidige project waar we bezig zijn is er een discussie rondom het 'id' en de 'code' voor communicatie in de API. Neem als voorbeeld deze operatie: https://vereniging-corponet.github.io/vera-openapi/Ketenprocessen/BRG.html#/Relaties/readRelatieById 

Als ik het dus goed begrijp wordt verwacht dat deze koppeling met het ID uitwisseling vereist op technische sleutel en moeten andere systemen de technische sleutel van objecten gaan opslaan om communicatie met een resource mogelijk te maken. Ik snap oprecht deze keuze niet in de VERA API. Als we kijken naar de historie zien we dat koppelingen nooit op een technische sleutel waren maar op een functionele sleutel (persoonsnummer, vhe, etc). Ik heb nog nooit gekoppeld op de ID's van database veldjes. Dat is zover ik nu snap wel de bedoeling in de API's van VERA. Wij zijn ook van mening dat je persistence id's misschien het liefst wel niet moet willen delen, maar dat is een keus. In sommige applicaties van ons zal het ID hetzelfde zijn als de code. Maar in al deze gevallen concluderen we dat we uitwisseling op basis van code logischer vinden dan op basis van ID.  

Een praktisch voorbeeld van de impact.  Een implementatie van https://vereniging-corponet.github.io/vera-openapi/Ketenprocessen/BRG.html#/Relaties/readRelatieById van zien wij niet als een nuttige koppeling. Elke partij zal dan onze technische id's moeten opslaan terwijl in hun applicatie deze entiteit bekend is onder de 'code'. Het maakt ook dat we verplicht worden om onze database id's altijd terug te koppelen naar elke andere partij, terwijl we juist geen koppeling willen op deze id's. Het resulteerd erin dat we koppelen op code als toegang tot de resource logischer achten dan id.

Het querien van een enkele relatie is dus in de huidige implementatie het meest logisch via een GET met filters (https://brg.vera.io/v1/relaties?code=test). Dat maakt dat een heel aantal Restful principes buitenspel worden gezet die horen bij communicatie via path waarden. Bijvoorbeeld is het niet meer mogelijk om een GET op resource id aan te bieden. Een reddirect naar een Location (zoals we zien in sommige PUT methodes) is ook niet mogelijk. We kunnen geen 404 retouneren wanneer een resource op id niet kan worden gevonden (want het pad wordt niet gebruikt dus geen http code ondersteuning). Etc. 

Concreet
- Is mijn conclusie wel juist dat ID het technische ID moet zijn? Als dat niet zo is, wat is dan het onderscheid/verschil nog tussen de echte bedoeling van ID en code? 
- Als het ID inderdaad het technische ID is: Waarom is gekozen om id het technische id te maken van een resource en niet een deelbaar id. 

Verzoek:
- id hernoemen naar technischId (voor wie dat echt ergens nodig heeft)
- code als entry maken of code hernoemen naar id. 

Groet
Chris

**Comment by kngspallett** [comment]
Hoi @cwiesenekker,

Bedankt voor jouw bericht. Naar verwachting zullen wij vrijdag een reactie sturen op jouw aangemelde issue. Mocht dit onverhoopt niet lukken dan laat ik dit uiteraard ook weten. 

Met vriendelijke groet,

Thomas Pallett

**Comment by kngspallett** [comment]
Goedemorgen @cwiesenekker,

Het gebruik van 'id' als ingang is volgens de Open API standaard gangbaar. Voor het gebruik van id's (en code) heeft VERA een pagina gepubliceerd. Op deze pagina kan je duiding en voorbeelden vinden over hoe de verschillende velden ingezet/uitgewisseld worden. Onderaan mijn bericht heb ik een URL gedeeld waarin je deze informatie kan terugvinden. Ik hoop dat je daarmee dan ook de duidelijkheid krijgt waar naar je op zoek bent. Mochten er toch nog vragen of opmerkingen zijn na het lezen van de documentatie dan hoor ik het graag. 

Met vriendelijke groet,

Thomas Pallett

https://cora.wikixl.nl/index.php/Gebruik_ID_in_VERA
