### ISSUE TITLE
Gebruik het liefst geen afkortingen (of mnomics) meer in naamgevingen

### ISSUE THREAD

**Issue by cwiesenekker** [vereniging-corponet/vera-openapi#2]
Voor alle naamgevingen, schrijf de naamgevingen volledig uit. Stap af van die mnomics. Het maakt het lezen veel moelijker. 

Neem ook dit voorbeeld https://github.com/vereniging-corponet/vera-openapi/blob/76404a7931b65ded0699ba6237013844b92943e9/Ketenprocessen/BDO.yaml#L3

Ketenprocess BDO gaat dus over casemanagement. Die link leg je niet zonder een dosis kenins van VERA.

**Comment by peterjanvandeput** [comment]
Mee eens
