### ISSUE TITLE
Vertrekdatum is toch een date en geen date-time?

### ISSUE THREAD

**Issue by pfheek** [vereniging-corponet/vera-openapi#29]
https://github.com/Aedes-datastandaarden/vera-openapi/blob/9e5ad27f6fe0a58c69d80412778eff6b32344634/Ketenprocessen/WRV.yaml#L7440C11-L7440C28

**Comment by MarcelVanDenBos** [comment]
Dank voor je feedback. We hebben het aangepast in patch 3
