### ISSUE TITLE
Informatie in verband met referentiedata

### ISSUE THREAD

**Issue by BvDEV397** [vereniging-corponet/vera-openapi#9]
Beste,

ik had graag 2 vragen:

1) In verband met de Excel over Referentiedata zie ik de code BEH tweemaal voor relatierolsoort. Zowel voor Behandelaar als Beheerder.

2) Voor het veld BOG:Overeenkomst:Opzegtermijn zie ik dit wel op cora.wiki maar niet in de openapi of referentiedata excel. Kan deze toegevoegd worden? ook eenheden_adres:buurt,wijk,woonplaats

3) Kan het zijn dan BOG.yml en BRG.yml circulaire dependencies bevatten?

Alvast hartelijk dank,
met vriendelijke groeten

**Comment by BvDEV397** [comment]
Heeft u hier al naar kunnen kijken?

**Comment by peterjanvandeput** [comment]
Dank voor je vragen !!

Excuus voor de late reactie.

Punt 1: dit is gewijzigd, Behandelaar is BED geworden

Punt 2: Opzegtermijn is aanwezig in de API (viewer: https://vereniging-corponet.github.io/vera-openapi/Ketenprocessen/BOG.html). Bij schema Overeenkomsten-overeenkomst zie je de verschillende soorten overeenkomst, als je daar 1 van uitklapt vind je veld Opzegtermijn. In de referentiedata vind je ook OPZEGTERMIJN met waarden: 12M | 12 maanden, 1M | 1 maand, 3M | 3 maanden, 4W | 4 weken en 6M | 6 maanden.

Punt 3: We proberen dat wel te voorkomen, als het goed is komt het in de laatste patch niet voor

Hartelijke groet!
